.TH COPYFS-MOUNT "1" "May 2008" "copyfs-mount" "User Commands"
.SH NAME
copyfs-mount \- mounts a versioned file system
.SH SYNOPSIS
.B copyfs-mount \fIversion-directory\fR \fImount-point\fR
.SH DESCRIPTION
This script lets you mount a CopyFS file system. \fIversion-directory\fR
is the directory where the files and version information will be stored by
CopyFS.

When using CopyFS for the first time, copyfs-mount will create
the required files in the \fIversion-directory\fR before running
copyfs-daemon. \fImount-point\fR is the directory where the copyfs
file system will be mounted. This is where the users will have access
to the files.

If you want to mount a CopyFS at '/mnt/fs', whose version directory is
at /var/versions, you would use:

	\fBroot@host# copyfs-mount /var/versions /mnt/fs\fR

To unmount it, simply do:

	\fBroot@host# umount /mnt/fs\fR

As you would do for any other filesystem.

You can also allow an ordinary non-root users to mount and unmount CopyFS
filesystems provided that the user is added to the 'fuse' group. Ordinary
users will be able unmount the filesystem, using the \fIfusermount\fR
command:

	\fB$ fusermount \-u \fImount-point\fR \fR

.SH AUTHORS
CopyFS was created by Thomas Joubert and Nicolas Vigier <boklm@mars-attacks.org>
.SH LINKS

<http://n0x.org/copyfs/> CopyFS web site.

<http://fuse.sourceforge.net/> FUSE - Filesystem in USErspace

.SH SEE ALSO
copyfs(1), copyfs-fversion(1), copyfs-daemon(1), fusermount(1)
